### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [jwagner/terrain#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by jwagner** [comment]
This is not open source. It's not licensed. Regular copy right applies, all rights reserved. But there is of course nothing stopping you from reading the code here on github. One thing worth noting is that these webgl projects were just demos/experiments. The code is not particularly clean or necessarily production ready.Things like WebGL context loss or resizing the window might not be handled (correctly).
